fix(CB): build graph typo
aws/aws-cryptographic-material-providers-library-java pull request #36
Opened 2023-06-07 20:39 UTC by josecorella

*Issue #, if available:*

*Description of changes:*

*Squash/merge commit message, if applicable:*

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2023-06-07 21:49 UTC, texastony requested changes
I don't think we need this.
This was for a hot fix test, right?

2023-06-07 22:59 UTC, josecorella commented
@texastony updated; we do need the file rename

2023-06-08 16:23 UTC, texastony approved these changes

2023-06-09 22:03 UTC, texastony approved these changes

2023-06-09 22:40 UTC, merged