feat: Update keystore structure
aws/aws-cryptographic-material-providers-library-java pull request #62
Opened 2023-07-18 16:40 UTC by seebees

Implement the specification changes to update the keystore structure.
Also adds input to the CreateKey operation
to allow creating a specific branch key id
as well as adding custom encryption context to a branch key.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2023-07-19 23:15 UTC, josecorella requested changes

2023-07-19 23:15 UTC, josecorella commented on AwsCryptographicMaterialProviders/dafny/AwsCryptographyKeyStore/src/KMSKeystoreOperations.dfy
> +      // && ParseAwsKmsIdentifier(reEncryptResponse.KeyId.value).Success?,
```suggestion
```

2023-07-20 03:13 UTC, seebees commented on AwsCryptographicMaterialProviders/dafny/AwsCryptographyKeyStore/src/DDBKeystoreOperations.dfy
> +      && old(ddbClient.History.TransactWriteItems) == ddbClient.History.TransactWriteItems
Yes, we do need it.
This is a specification that says we are not doing `TransactWriteItems`.
Without this, Dafny would not believe that `TransactWriteItems` History is unchanged.

2023-07-20 03:18 UTC, seebees commented on AwsCryptographicMaterialProviders/dafny/AwsCryptographyKeyStore/src/GetKeys.dfy
> +    // && |kmsClient.History.Decrypt| == |old(kmsClient.History.Decrypt)| + 1
Moved to a better place

2023-07-20 04:39 UTC, josecorella approved these changes
lgtm

2023-07-20 13:52 UTC, merged